var quotes = [
    "Click. Boom. &iexcl;Asombroso!//Steve Jobs//fav",
    "El diseño no es sólo cómo se ve o cómo se siente. El Diseño es cómo funciona//Steve Jobs//Paulo Nunes",
    "¿Por qué enrolarse en la armada cuando puedes ser un pirata?//Steve Jobs",
    "La innovación distingue entre un líder y un seguidor//Steve Jobs",
    "La calidad es más importante que la cantidad. Un 'home run' es mucho mejor que dos dobles//Steve Jobs//DaLancelotBruh//twitter",
    "Hay gente que lo único que quiere es ver arder el mundo//Alfred, Batman//DaLancelotBruh//twitter",
    "Si se te da bien algo, nunca lo hagas gratis…//Joker, Batman//DaLancelotBruh//twitter",
    "Ya no puedes fiarte de nadie. Si quieres algo, tienes que hacerlo tú, ¿no crees?//Joker, Batman//DaLancelotBruh//twitter",
    "No es sino la sombra de una ilusion lo que amas, no puedo darte lo que anhelas//Aragorn, El Se&ntilde;or de los Anillos//lorenzo.v.matterhorn.948//facebook",
    "&iexcl;Algebraico!//Finn el Humano, Hora de Aventuras//toofartooblack//tumblr//fav",
    "Veni, vidi, vinci//Julio Cesar//lorenzo.v.matterhorn.948//facebook",
    "Lo que hacemos en nuestras vidas tiene su eco en la eternidad//Maximo Decimo Meridio, Gladiator//lorenzo.v.matterhorn.948//facebook",
    "Hazlo, o no lo hagas, pero no lo intentes//Yoda, Star Wars//lorenzo.v.matterhorn.948//facebook",
    "Relaxing cup of caf&eacute; con leche in Plaza Mayor//Ana Botella//lorenzo.v.matterhorn.948//facebook",
    "Con el ojo por ojo, al final todos ciegos//Mahatma Gandhi//Alex Coll",
    "Es el sindrome FLictonic CLipple Weber//Haruko Haruhara, Furi Curi//DaLancelotBruh//twitter//fav",
    "La ciudad se llenó de humo, olvidando que ahí fuera existe un mundo. No hay cosas extraordinarias, vives en un mundo donde sólo hay cosas obvias. Una vida entera que espera morir lentamente... Pero Haruko está aquí y yo no olvido que existe un mundo ahí fuera.//Raharu Haruha, Furi Curi//DaLancelotBruh//twitter//fav",
    "Con un ejercito detras se puede ser sumamente politico//Gayo, Gladiator//lorenzo.v.matterhorn.948//facebook",
    "Instaura una pequeña anarquía, altera el orden establecido, y comenzará a reinar el caos. Soy un agente del caos. ¿Y sabes qué tiene el caos? Que es justo//Joker, Batman//toofartooblack//tumblr",
    "&iexcl;ESTO ES ESPARTA!//Leonidas, 300 La Pelicula//lorenzo.v.matterhorn.948//facebook",
    "Quisiera volver a verte hoy mismo, pero estoy dispuesto a esperar toda la noche y buena parte de ma&ntilde;ana//Augustus Waters, Bajo la misma Estrella//toofartooblack//tumblr//fav",
    "Oh, no me importaría Hazel Grace. Sería un privilegio que me rompieras el coraz&oacute;n//Augustus Waters, Bajo la misma Estrella//toofartooblack//tumblr//fav",
    "Es una metafora. Te colocas el arma asesina entre los dientes, pero no le das el poder de matarte//Augustus Waters, Bajo la misma Estrella//toofartooblack//tumblr//fav",
    "Aceptamos el amor que creemos merecer//Profesor Bill, Ventajas de Ser un Marginado//toofartooblack//tumblr//fav",
    "Yo no soy un monstruo... sólo voy un paso por delante//Joker, Batman//toofartooblack//tumblr//fav"
];